// auto-generated by ContractResolver
// Generated: 2026-03-21T16:29:02.776Z
// Total tokens: 8

module.exports = [
    {
        symbol: "BAN",
        dex: {
            solana: "9PR7nCP9DpcUotnDPVLUBUZKu5WAYkwrCUx9wDnSpump"
        },
        cex: {
            gateio: "BAN/USDT"
        }
    },

    {
        symbol: "BERT",
        dex: {
            solana: "HgBRWfYxEfvPhtqkaeymCQtHCrKE46qQ43pKe8HCpump"
        },
        cex: {
            gateio: "BERT/USDT"
        }
    },

    {
        symbol: "FARTCOIN",
        dex: {
            solana: "9BB6NFEcjBCtnNLFko2FqVQBq8HHM13kCyYcdQbgpump"
        },
        cex: {
            gateio: "FARTCOIN/USDT"
        }
    },

    {
        symbol: "MUBARAK",
        dex: {
            bsc: "0x5c85d6c6825ab4032337f11ee92a72df936b46f6"
        },
        cex: {
            gateio: "MUBARAK/USDT"
        }
    },

    {
        symbol: "PIPPIN",
        dex: {
            solana: "Dfh5DzRgSvvCFDoYc2ciTkMrbDfRKybA4SoFbPmApump"
        },
        cex: {
            gateio: "PIPPIN/USDT"
        }
    },

    {
        symbol: "SIREN",
        dex: {
            bsc: "0x997a58129890bbda032231a52ed1ddc845fc18e1"
        },
        cex: {
            gateio: "SIREN/USDT"
        }
    },

    {
        symbol: "TRUMP",
        dex: {
            solana: "6p6xgHyF7AeE6TZkSmFsko444wqoP15icUSqi2jfGiPN"
        },
        cex: {
            gateio: "TRUMP/USDT"
        }
    },

    {
        symbol: "USELESS",
        dex: {
            solana: "Dz9mQ9NzkBcCsuGPFJ3r1bS4wgqKMHBPiVuniW8Mbonk"
        },
        cex: {
            gateio: "USELESS/USDT"
        }
    }
];
